spring.application.name: video-hits

rabbitmq:
   connection:
      username: guest
      password: guest
      host: localhost
      port: 5672
   queue:
      video-hit: "video-hit.video-hits"
      dead-letter: "DLQ"
   exchange:
      video-hit: "video-hit"
      dead-letter: "DLX"